### ISSUE TITLE
14C calibration curves (Ubuntu)

### ISSUE THREAD

**Issue by nfrerebeau** [Chronomodel/chronomodel#104]
I made a fresh install of ChronoModel 2.0.18 (February 2019 release) on Ubuntu 18.04 LTS (64 bit system) and I am facing some issue with the 14C calibration curves.

In the application Settings there is no curve provided (which is not a problem by itself). I downloaded intcal13.14c from [here](http://www.radiocarbon.org/IntCal13.htm), but when I try to add it through the application Settings (as explained in the [FAQ](https://chronomodel.com/chronomodel-frequently-asked-questions-faq)) the curve name is displayed in red and disappear if I close and reopen the window.

Do I have to format the file in a certain way (I tried by removing the header but without success) or put it in a specific folder?

**Comment by chrono35** [comment]
Hi,
If you are not "administrator", you can have this trouble. Because ChronoModel must to find the calibration curves in a hidden folder in your home dir.
 It's Ok with the linux policy.

# The solution
Open a terminal wihtin your download directory or your folder with the ChronoModel.deb .
Run the following commands one by one or create a bash file ( InstallCalibration.sh) with a text editor using a copy/paste method :

```bash
#!/bin/bash
# 1 - Clean the directory, if exist 
rm -rf ~/.local/share/CNRS  

# 2 - Create a new directory for the calibration curves
mkdir -p ~/.local/share/CNRS/ChronoModel  	

# 3 - Extract the calibration curve in a folder "tmpFolder"
dpkg-deb -x ChronoModel\ 2.0\ \(February\ 2019\).deb tmpFolder

# 4 - Copy the Calibration curve
cp -r tmpFolder/tmp/chronomodel/Calib ~/.local/share/CNRS/ChronoModel/  

# 4 - Remove	the tmpFolder
rm -rf tmpFolder							

# 5 - Execute the ChronoModel processus
chronomodel
```
_If you do a bash file, execute this in the terminal :
sh InstallCalibration.sh_

Let me know

**Comment by nfrerebeau** [comment]
It worked just fine, thanks!
